image: node:22.18.0

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /push|web/'
      when: always
    - when: never

stages:
  - installation
  - build
  - triggers

variables:
  npm_config_cache: '${CI_PROJECT_DIR}/.npm'
  NPM_VERSION: '11.6.2'

before_script:
  - npm i -g npm@${NPM_VERSION}

installation:
  stage: installation
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: push
    paths:
      - node_modules
      - '**/node_modules'
      - .npm
  script:
    - npm ci

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull-push
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
      - .npm
  script:
    - npm run build

run_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/workflows/ci.yml
    strategy: mirror

run_snapshot_publish:
  stage: triggers
  rules:
    - when: manual
  allow_failure: true
  trigger:
    include:
      - local: .gitlab/workflows/snapshot-publish.yml
    strategy: mirror
