image: $GITLAB_CI_IMAGE

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /push|web/'
      when: always
    - when: never

include:
  - component: $CI_SERVER_FQDN/${ROOT_COMPONENT}

    inputs:
      enable_ci_child: true
      enable_snapshot_publish_child: true
