image: node:22.18

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /push|web/'
      when: always
    - when: never

stages:
  - installation
  - build
  - triggers

installation:
  stage: installation
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
      - '**/node_modules'
  script:
    - npm ci

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: pull-push
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run build

run_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/workflows/ci.yml
    strategy: mirror

run_snapshot_release:
  stage: triggers
  rules:
    - when: manual
  allow_failure: true
  trigger:
    include:
      - local: .gitlab/workflows/snapshot-release.yml
    strategy: mirror
