image: $GITLAB_CI_IMAGE

default:
  interruptible: true

workflow:
  auto_cancel:
    on_job_failure: all

stages:
  - ci

knip:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
  script:
    - npx knip --dependencies

type_check:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run type-check

lint:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
  script:
    - npm run lint:check

test:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - '**/node_modules'
      - '**/dist'
  script:
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: '**/coverage/cobertura-coverage.xml'

changeset:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
  before_script:
    - git fetch origin dev
  script:
    - npx changeset status --since=origin/dev
